### ISSUE TITLE
Standardizing Frontend/Backend Communication Using JSON

### ISSUE THREAD

**Issue by steffen12** [keepid/keepid_server#51]
Right now, we need to make everything communicate using JSON - it is actually pretty messed up right now.

On the server, we use a mix of ctx.json and ctx.result
And even within ctx.json, sometimes we are sending a string, and sometimes JSON object

On the client, we use JSON.parse() and result => result.json(), while we should not use JSON.parse at all

We need to standardize this

**Comment by crchong1** [comment]
this is fixed with the backend service change. there might be some exceptions that still need to be dealt with, but this is basically done
