### ISSUE TITLE
Testing Audit

### ISSUE THREAD

**Issue by kofmangregory** [keepid/keepid_server#56]
We are embarking on a journey to eliminate our unit test debt. The start of this journey is figuring out how much unit test debt we have.

For each publicly exposed method `M` in our controllers and utility files, it would be great to assess the following:

1. Is each unit of work done by `M` tested?
2. Does each test case that tests `M` test a single unit of work?

If the answer to these questions is "No" for a substantial number of methods, then we should answer the following:

3. Does our testing structure make it difficult to write complete tests, or have we just been lazy with the completeness of our tests?
4. Can we design a system for writing tests that makes it easier to test each unit of work done by each method? What are the current limitations to this?

**Comment by crchong1** [comment]
@kofmangregory is it possible to divide people based on areas of the code for the test audit? It's not as clear who is looking at which code and making sure there's no overlap. Unless you want everyone to look at all the tests. Also would be good to make a google doc to keep track of all the results
