### ISSUE TITLE
Create an OrganizationDao, OrganizationDaoImpl, OrganizationDaoTestImpl, and OrganizationDaoFactory

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_server#65]
Copy from the UserDao in the training server, and write a simple Dao object layer for the organization and getting organizations in the database.

**Comment by crchong1** [comment]
It would be really pref if you would also update all the unit tests around organizations to use the new OrganizationDao

**Comment by avwu99** [comment]
[https://github.com/keepid/keepid_server/tree/orgDAO](url) - Branch with orgDAO
So, it turns out we actually don't have unit tests for orgs that would need to utilize an in memory database atm.... everything's an integration test lol

**Comment by crchong1** [comment]
yup so we need to write unit tests haha
