### ISSUE TITLE
Wrong Profile Photo Returned & Slow Get Activities

### ISSUE THREAD

**Issue by MelindaCardenas** [keepid/keepid_server#68]
The load-pfp seems to not always be returning the most recent pfp but instead going through an array (or something like that) and sometimes it will loose it's place and then send back previously uploaded photos (still maintaining the chronological order just not giving back the most recent photo)

I attached a zip file of a video showing the issue i'm talking about 
[returning_wrong_image.mov.zip](https://github.com/keepid/keepid_server/files/5579772/returning_wrong_image.mov.zip)

Also, the get activities seems to take a while in returning a value even if there aren't any activities. I haven't looking into this so much, it can be possible it's something on my end (frontend). But if you think there's any way to make this process faster then that would be great!

**Comment by crchong1** [comment]
I think this is done? @MelindaCardenas @cccyyyr

**Comment by crchong1** [comment]
feel free to close if it is
