### ISSUE TITLE
When Annotated PDF is uploaded, it is marked as annotated in database

### ISSUE THREAD

**Issue by steffen12** [keepid/keepid_server#7]
Person can upload an annotated pdf and it will replace the old pdf form
Mark in the database now that the pdf is annotated

**Comment by abhishekp106** [comment]
PDFUpload now has a new form parameter - `fileId`. If there is a `fileId`, then it will replace the already existing file, and replace it with the one given, and it will be marked as annotated.

Created a new method mongodbUploadAnnotatedForm to do this.
