### ISSUE TITLE
Integration Tests for PDFController

### ISSUE THREAD

**Issue by steffen12** [keepid/keepid_server#8]
Still need to do int tests for Application related routes

**Comment by abhishekp106** [comment]
PdfController.getFieldInformation: small bug that wouldn't allow JSONArray of `"fieldValueOptions"` to be put in `fieldJSON` properly (a string was put in, not a JSON Array, leading to a bug when trying to return all fields in the annotated form). Fixed.

**Comment by abhishekp106** [comment]
Fixed bug: if acroForm is null (meaning no fields), simply return and keep fieldsJSON empty.
